title: Sam 'Ismail' Savruk # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Learner, Educator, Data Scientist
  <br><br>
  <a href="https://www.linkedin.com/in/ismailsavruk/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
